app:
    resource: "@AppBundle/Controller/"
    type:     annotation

user_login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }

user_register:
    path:     /register
    defaults: { _controller: AppBundle:Registration:register }

user_posts:
    path:     /user/posts
    defaults: { _controller: AppBundle:User:showPosts }

user_post_check:
    path:     /user/post_check
    defaults: {_controller: AppBundle:User:sendPost }

user_messagerie:
    path:     /user/messagerie
    defaults: { _controller: AppBundle:User:messagerie }

message_check:
    path:     /user/messagerie_check
    defaults: {_controller: AppBundle:User:sendmsg}

user_profil:
    path:     /user/profil
    defaults: { _controller: AppBundle:User:showProfil }    

user_accueil:
    path:     /user/accueil
    defaults: { _controller: AppBundle:Registration:register }

profil_check:
    path:     /user/profil_check
    defaults: {_controller: AppBundle:User:modify }

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
