app:
    resource: "@AppBundle/Controller/"
    type:     annotation

user_login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }

user_register:
    path:     /register
    defaults: { _controller: AppBundle:Registration:register }

user_messagerie:
    path:     /user/messagerie
    defaults: { _controller: AppBundle:Registration:register }

user_profil:
    path:     /user/profil
    defaults: { _controller: AppBundle:Registration:register }    

user_accueil:
    path:     /user/accueil
    defaults: { _controller: AppBundle:Registration:register }
# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
