app:
    resource: "@AppBundle/Controller/"
    type:     annotation

user_login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }

user_register:
    path:     /register
    defaults: { _controller: AppBundle:Registration:register }

# ==== Profil ====
user_profil:
    path:     /user/profil
    defaults: { _controller: AppBundle:User:showProfil }

other_profil:
    path:     /user/profil/{id}
    defaults: {_controller: AppBundle:User:showOtherProfil}

profil_check:
    path:     /user/profil_check
    defaults: {_controller: AppBundle:User:modifyProfil }

# ==== Post ====
user_accueil:
    path:     /user/accueil
    defaults: { _controller: AppBundle:User:showAllPosts }

user_posts:
    path:     /user/post
    defaults: { _controller: AppBundle:User:showPosts }

user_post_check:
    path:     /user/post_check
    defaults: {_controller: AppBundle:User:sendPost }

# ==== Messagerie ====
user_messagerie:
    path:     /user/messagerie
    defaults: { _controller: AppBundle:User:showMessages }

message_check:
    path:     /user/messagerie/send
    defaults: {_controller: AppBundle:User:sendMessage}

message_delete:
    path:     /user/messagerie/delete/{id}
    defaults: {_controller: AppBundle:User:deleteMessage}

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
